# Generated by Django 3.2.9 on 2021-12-13 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('award', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_value', models.IntegerField(blank=True, default=0, null=True)),
                ('usability_value', models.IntegerField(blank=True, default=0, null=True)),
                ('content_value', models.IntegerField(blank=True, default=0, null=True)),
                ('average_value', models.IntegerField(blank=True, default=0, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
